version: '3.8'

networks:
  frontend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
  backend:
    driver: bridge
    internal: true  # No external access
    ipam:
      config:
        - subnet: 172.21.0.0/16

volumes:
  caddy_data:
  caddy_config:
  pocketbase_data:
  logs:

secrets:
  pb_admin_email:
    file: ./secrets/pb_admin_email.txt
  pb_admin_password:
    file: ./secrets/pb_admin_password.txt

services:
  caddy:
    image: caddy:2-alpine
    container_name: caddy
    restart: unless-stopped
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
      - DAC_OVERRIDE
    security_opt:
      - no-new-privileges:true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
      - logs:/var/log/caddy
    networks:
      - frontend
    environment:
      - CADDY_INGRESS_NETWORKS=frontend
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:2019/config/"]
      interval: 30s
      timeout: 5s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nextjs:
    build:
      context: .
      dockerfile: docker/Dockerfile.nextjs
    container_name: nextjs
    restart: unless-stopped
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /app/.next/cache
    networks:
      - frontend
      - backend
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_POCKETBASE_URL=http://pocketbase:8090
      - NEXT_PUBLIC_SITE_URL=https://andub.go.ro
    env_file:
      - .env.production
    depends_on:
      pocketbase:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 256M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  pocketbase:
    build:
      context: .
      dockerfile: docker/Dockerfile.pocketbase
    container_name: pocketbase
    restart: unless-stopped
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
    networks:
      - backend
    volumes:
      - pocketbase_data:/pb/pb_data
      - ./pb_migrations:/pb/pb_migrations:ro
    secrets:
      - pb_admin_email
      - pb_admin_password
    environment:
      - PB_ENCRYPTION_KEY=${PB_ENCRYPTION_KEY}
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Security monitoring container
  fail2ban:
    image: crazymax/fail2ban:latest
    container_name: fail2ban
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./fail2ban:/data
      - logs:/var/log/caddy:ro
      - /var/log:/var/log/host:ro
    environment:
      - TZ=UTC
      - F2B_LOG_LEVEL=INFO
      - F2B_DB_PURGE_AGE=7d
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"