all:
  vars:
    ansible_user: VespianRex
    ansible_ssh_private_key_file: /Users/alex/.ssh/id_ed25519_clarity
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    vip: 192.168.0.51
    domain: andub.go.ro
    domain_base: andub.go.ro
    letsencrypt_email: ops@andub.go.ro
    nfs_server: 192.168.0.55
    nfs_export: /volume1/proxmox-shared
    nfs_path: /volume1/proxmox-shared
    app_ip: 192.168.0.180
    monitoring_ip: 192.168.0.207
    vpn_port: 1194

  children:
    edge:
      hosts:
        edge-primary:
          ansible_host: 192.168.0.192
          keepalived_state: MASTER
          keepalived_priority: 100
          edge_priority: 100
          keepalived_password: ClarityEdgePass
          keepalived_router_id: 51
          vm_role: edge

    app:
      hosts:
        clarity-app:
          ansible_host: 192.168.0.180
          vm_role: application

    monitoring:
      hosts:
        monitoring:
          ansible_host: 192.168.0.207
          vm_role: monitoring

    pbs:
      hosts:
        pbs-backup:
          ansible_host: 192.168.0.242
          vm_role: backup

    nfs:
      hosts:
        nfs-storage:
          ansible_host: 192.168.0.144
          vm_role: nfs-client

    synology:
      hosts:
        synology-nas:
          ansible_host: 192.168.0.55
          ansible_user: admin
          ansible_password: M4r34N34gr4
          ansible_become_password: M4r34N34gr4
